#!/bin/bash
set -e

LOG="/var/log/supabase-bootstrap.log"
exec > >(tee -a "$LOG") 2>&1
echo "[$(date)] Bootstrap: start"

# ===== Stage 1: Install Docker CE (official mirror) =====
echo "[$(date)] Installing Docker CE..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y ca-certificates curl gnupg lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
apt-get update -y
apt-get install -y docker-ce docker-compose-plugin
echo "[$(date)] Docker installed: $(docker --version)"

# ===== Stage 2: Download config and generate .env =====
echo "[$(date)] Downloading Supabase config..."
mkdir -p /opt/supabase/volumes/api /opt/supabase/volumes/db
cd /opt/supabase

OBS_BASE="${OBS_BASE_URL:-https://tp-00940108.obs.ap-southeast-3.myhuaweicloud.com}/supabase/intl/ap-southeast-3/standard"
wget -q "$OBS_BASE/docker-compose.yaml" -O docker-compose.yaml
wget -q "$OBS_BASE/kong.yml" -O volumes/api/kong.yml

# Parameters: db_password jwt_secret
DB_PASSWORD="${1?Usage: install_supabase.sh <db_password> [jwt_secret]}"
JWT_SECRET="${2:-$(openssl rand -base64 32 2>/dev/null || echo 'change-me-secret-key')}"
SECRET_KEY_BASE="$(openssl rand -base64 32 2>/dev/null || echo 'supabase-secret-key-base')"

cat > .env << ENVEOF
# Supabase environment config (auto-generated by deploy script)
POSTGRES_PASSWORD=${DB_PASSWORD}
JWT_SECRET=${JWT_SECRET}
SECRET_KEY_BASE=${SECRET_KEY_BASE}
APP_NAME=supabase
ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTAyNzN9.CRXP1A7WOeoJeXxjNni43kdEDwNnnP7IGiD1k3ivLc0
SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMDI3M30.sQTxYmZxLJmhFIVwYl_cfMZMZNmrUIMmF8v3Rj7obI0
ENVEOF

# ===== Stage 3: Deploy containers =====
echo "[$(date)] Deploying Supabase..."
cd /opt/supabase

MAX_RETRIES=5
COUNT=0
deploy_ok=0
until [ $COUNT -ge $MAX_RETRIES ]; do
  docker compose pull 2>&1 && docker compose up -d 2>&1 && deploy_ok=1 && break
  COUNT=$((COUNT+1))
  echo "[$(date)] Pull/start failed (attempt $COUNT/$MAX_RETRIES), retrying in 30s..."
  sleep 30
done

if [ $deploy_ok -eq 0 ]; then
  echo "[FATAL] Deploy failed, check logs"
  docker compose logs --tail=50 2>&1 || true
  exit 1
fi
echo "[$(date)] Containers started"

# ===== Stage 3.5: DB initialization =====
echo "[$(date)] Waiting for DB ready..."
for i in $(seq 1 30); do
  docker exec supabase-db pg_isready -U postgres -q 2>/dev/null && break
  sleep 2
done

HAS_PW=$(docker exec supabase-db psql -U postgres -t -A -c \
  "SELECT count(*) FROM pg_shadow WHERE usename IN ('authenticator','supabase_auth_admin','supabase_storage_admin') AND passwd IS NOT NULL;" 2>/dev/null || echo "0")

if [ "$HAS_PW" != "3" ]; then
  echo "[INFO] Initializing database roles and schema..."
  docker exec supabase-db psql -U postgres -c "CREATE DATABASE supabase;" 2>/dev/null || true
  docker exec -e PGPASSWORD=$DB_PASSWORD supabase-db psql -U supabase_admin -h localhost \
    -d postgres -c "ALTER USER authenticator WITH PASSWORD '$DB_PASSWORD';" 2>/dev/null || true
  docker exec -e PGPASSWORD=$DB_PASSWORD supabase-db psql -U supabase_admin -h localhost \
    -d postgres -c "ALTER USER supabase_auth_admin WITH PASSWORD '$DB_PASSWORD';" 2>/dev/null || true
  docker exec -e PGPASSWORD=$DB_PASSWORD supabase-db psql -U supabase_admin -h localhost \
    -d postgres -c "ALTER USER supabase_storage_admin WITH PASSWORD '$DB_PASSWORD';" 2>/dev/null || true
  docker compose restart auth rest storage realtime 2>/dev/null || true
  echo "[OK] Database initialization complete"
fi

# ===== Stage 4: Health check =====
echo "[$(date)] Health check..."
sleep 15
echo "--- Container status ---"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
echo "--- Dashboard check ---"
curl -sS --connect-timeout 5 http://localhost:8000/project/default 2>&1 | head -3 || echo "Dashboard not ready (may need more time)"
echo "[$(date)] Bootstrap: complete"
echo ""
echo "====================================================="
echo " Dashboard: http://YOUR_EIP:8000/project/default"
echo " Log: /var/log/supabase-deploy/"
echo " Config: /opt/supabase/"
echo "====================================================="
