"use client"

import { useMemo, useState } from "react"
import Link from "next/link"
import { AlertTriangle, ArrowRight, CheckCircle2, CircleDot, FileCode2, Globe2, LockKeyhole, Network, ShieldAlert } from "lucide-react"
import type { WorkbenchSnapshot } from "@/lib/workbench"
import { getArchitectureProfile } from "@/lib/architecture"
import { cn } from "@/lib/utils"

export function ArchitectureWorkspace({ snapshot }: { snapshot: WorkbenchSnapshot }) {
  const [slug, setSlug] = useState(snapshot.practices[0]?.slug ?? "litellm")
  const practice = snapshot.practices.find(item => item.slug === slug) ?? snapshot.practices[0]
  const [variant, setVariant] = useState(practice?.hasHA ? "ha" : "standard")
  const profile = useMemo(() => getArchitectureProfile(slug, variant) ?? getArchitectureProfile("litellm"), [slug, variant])!
  const [selected, setSelected] = useState(profile.nodes[0]?.id)
  const node = profile.nodes.find(item => item.id === selected) ?? profile.nodes[0]
  const checks = snapshot.audit.results.filter(item => item.practice.startsWith(`${slug}/`))
  const errors = checks.reduce((sum, item) => sum + item.errors, 0)
  const warnings = checks.reduce((sum, item) => sum + item.warnings, 0)

  function selectPractice(next: string) { const item = snapshot.practices.find(value => value.slug === next); setSlug(next); setVariant(item?.hasHA ? "ha" : "standard"); setSelected("internet") }

  return <div className="px-5 md:px-10 py-8 md:py-12 max-w-[1500px] mx-auto space-y-7">
    <header className="flex flex-wrap items-end justify-between gap-5 border-b border-border pb-7"><div><div className="eyebrow">Architecture Center · Evidence Workspace</div><h1 className="heading-lg text-ink mt-3">架构工作区</h1><p className="text-sm text-ink-faded mt-3 max-w-3xl leading-6">选择一个正式部署实例，查看资源拓扑、变量合同、公开入口、风险和质量证据。拓扑中的推导关系会明确标注，不冒充 Terraform Plan。</p></div><Link href={`/practices/${slug}`} className="inline-flex items-center gap-2 rounded-lg border border-border bg-surface px-4 py-2.5 text-sm font-bold text-ink hover:border-ink">打开方案详情 <ArrowRight className="h-4 w-4" /></Link></header>

    <section className="grid gap-4 lg:grid-cols-[18rem_1fr_20rem]">
      <aside className="rounded-2xl border border-border bg-surface p-4 shadow-soft h-fit"><div className="eyebrow px-2">Instance Selector</div><div className="mt-3 space-y-1">{snapshot.practices.map(item => <button key={item.slug} onClick={() => selectPractice(item.slug)} className={cn("w-full rounded-xl px-3 py-3 text-left transition", item.slug === slug ? "bg-ink text-cream" : "hover:bg-cream text-ink")}><span className="flex items-center justify-between gap-3"><span className="text-sm font-bold">{item.name}</span>{item.hasHA && <span className={cn("text-[0.62rem]", item.slug === slug ? "text-cream/55" : "text-ink-muted")}>HA</span>}</span><span className={cn("block text-[0.68rem] mt-1", item.slug === slug ? "text-cream/60" : "text-ink-muted")}>{item.category} · {item.regions.length} 区域</span></button>)}</div><div className="border-t border-border mt-5 pt-5"><div className="eyebrow px-2">Variant</div><div className="grid grid-cols-2 gap-1 mt-3 rounded-lg bg-cream p-1">{(practice?.hasHA ? ["standard", "ha"] : ["standard"]).map(value => <button key={value} onClick={() => { setVariant(value); setSelected("internet") }} className={cn("rounded-md px-2 py-2 text-xs font-bold", variant === value ? "bg-ink text-cream" : "text-ink-muted")}>{value.toUpperCase()}</button>)}</div></div><div className="mt-5 rounded-xl bg-cream p-4"><div className="eyebrow">Contract State</div><div className="flex items-center gap-2 mt-2 text-sm font-bold text-amber-800"><AlertTriangle className="h-4 w-4" />草稿 / 待确认</div><p className="text-[0.68rem] text-ink-muted mt-2 leading-5">工作台不会替用户批准公网、域名、规格或生产发布决策。</p></div></aside>

      <section className="rounded-2xl border border-border bg-surface p-5 md:p-7 shadow-soft min-w-0"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="eyebrow">{profile.variant.toUpperCase()} · Rule-derived topology</div><h2 className="serif text-2xl font-bold text-ink mt-2">{profile.title}</h2><p className="text-sm text-ink-faded mt-2 max-w-2xl leading-6">{profile.summary}</p></div><span className="inline-flex items-center gap-1.5 rounded-full bg-blue-50 px-2.5 py-1 text-[0.65rem] font-bold text-blue-800"><CircleDot className="h-3 w-3" />推导视图</span></div><div className="mt-8 overflow-x-auto pb-3 overscroll-x-contain"><div className="flex w-max min-w-full items-stretch justify-center gap-3 px-1">{profile.nodes.map((item, index) => <div key={item.id} className="flex shrink-0 items-center gap-3"><button onClick={() => setSelected(item.id)} className={cn("w-40 min-h-28 rounded-xl border p-3 text-left transition", selected === item.id ? "border-accent bg-orange-50 shadow-[0_0_0_3px_rgba(201,100,66,.12)]" : "border-border bg-cream hover:border-ink/40")}><div className="flex items-center justify-between"><Network className={cn("h-4 w-4", item.zone === "edge" ? "text-accent" : item.zone === "data" ? "text-blue-600" : "text-ink-muted")} /><span className="text-[0.58rem] text-ink-muted">{item.kind}</span></div><div className="text-xs font-bold text-ink mt-3 break-words">{item.title}</div><div className="text-[0.62rem] text-ink-muted mt-1 leading-4 break-words">{item.note}</div></button>{index < profile.nodes.length - 1 && <ArrowRight className="h-4 w-4 shrink-0 text-ink-muted" />}</div>)}</div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Mini label="节点" value={profile.nodes.length} /><Mini label="链路" value={profile.edges.length} /><Mini label="质量错误" value={errors} tone={errors ? "danger" : "ok"} /></div><div className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-950"><Globe2 className="inline h-4 w-4 mr-2" />链路关系来自架构基线和资源类型推导。需要逐项证明的内容请点击节点查看源文件与质量检查，不把图形当作云端实时状态。</div></section>

      <aside className="rounded-2xl border border-border bg-surface p-5 shadow-soft h-fit"><div className="eyebrow">Inspector · 证据检查器</div><h2 className="serif text-xl font-bold text-ink mt-2">{node.title}</h2><div className="text-xs text-ink-muted mt-1">{node.kind} · {node.zone}</div><div className="mt-5 space-y-4"><Info icon={FileCode2} label="来源状态" value="规则推导" /><Info icon={LockKeyhole} label="公开边界" value={node.zone === "edge" ? "需确认公网入口" : "默认内网"} /><Info icon={ShieldAlert} label="相关质量" value={`${warnings} 个警告 · ${errors} 个错误`} /></div><div className="border-t border-border mt-5 pt-5"><div className="eyebrow">Contract Variables</div><div className="mt-3 flex flex-wrap gap-1.5">{profile.variables.map(item => <span key={item} className="rounded-md bg-cream px-2 py-1 text-[0.65rem] font-mono text-ink-faded">{item}</span>)}</div></div></aside>
    </section>

    <section className="grid gap-6 lg:grid-cols-3"><Contract title="客户可见变量" icon={FileCode2} items={profile.variables} note="来自模板变量；不展示默认密码或敏感值。" /><Contract title="固定值与规则" icon={CheckCircle2} items={profile.fixed} note="开发阶段不得在合同外新增端口、代理层或依赖。" /><Contract title="风险与偏差" icon={ShieldAlert} items={profile.risks} note="风险必须绑定门禁或人工确认，不自动隐藏。" /></section>
  </div>
}

function Mini({ label, value, tone }: { label: string; value: number; tone?: "danger" | "ok" }) { return <div className="rounded-xl bg-cream p-4"><div className="eyebrow">{label}</div><div className={cn("serif text-2xl font-bold mt-2", tone === "danger" ? "text-red-600" : tone === "ok" ? "text-emerald-700" : "text-ink")}>{value}</div></div> }
function Info({ icon: Icon, label, value }: { icon: typeof FileCode2; label: string; value: string }) { return <div className="flex items-center gap-3"><Icon className="h-4 w-4 text-accent shrink-0" /><div><div className="eyebrow">{label}</div><div className="text-sm font-bold text-ink mt-1">{value}</div></div></div> }
function Contract({ title, icon: Icon, items, note }: { title: string; icon: typeof FileCode2; items: string[]; note: string }) { return <article className="rounded-2xl border border-border bg-surface p-6 shadow-soft"><Icon className="h-5 w-5 text-accent" /><h2 className="serif text-xl font-bold text-ink mt-3">{title}</h2><div className="mt-5 space-y-2">{items.map(item => <div key={item} className="rounded-lg bg-cream px-3 py-2.5 text-xs text-ink-faded">{item}</div>)}</div><p className="text-[0.68rem] text-ink-muted mt-4 leading-5">{note}</p></article> }
