"use client"
import Link from "next/link"
import { ArrowRight, Download, MapPin } from "lucide-react"

export type CatalogItem = { slug: string; name: string; category: string; tagline: string; overview: string; sites: string[]; regions: string[]; variants: string[]; hasHA: boolean; hasDocs: boolean; errors: number; warnings: number }

export function SolutionCatalog({ items }: { items: CatalogItem[] }) {
  return <main className="px-5 md:px-10 py-8 max-w-[1500px] mx-auto space-y-7"><header><span className="eyebrow">Solution Center</span><h1 className="heading-lg text-ink mt-3">解决方案库</h1><p className="text-sm text-ink-faded mt-3">正式方案支持架构查看、Terraform 代码和方案文档下载。</p></header><div className="grid gap-5 xl:grid-cols-3">{items.map(item => <article key={item.slug} className="bg-surface rounded-2xl border border-border p-6 shadow-soft"><div className="eyebrow">{item.category}</div><h2 className="serif text-2xl font-bold text-ink mt-2">{item.name}</h2><p className="text-sm text-ink-faded mt-2">{item.tagline}</p><div className="mt-5 text-xs text-ink-muted">{item.regions.length} 个区域 · {item.variants.join(" / ").toUpperCase()}</div><div className="mt-6 flex flex-wrap gap-2"><Link href={`/practices/${item.slug}`} className="inline-flex items-center gap-1.5 rounded-lg bg-ink px-4 py-2 text-xs font-bold text-cream">查看架构 <ArrowRight className="h-3.5 w-3.5" /></Link><Link href={`/workspace?solution=${item.slug}`} className="inline-flex items-center gap-1.5 rounded-lg border border-border px-3 py-2 text-xs text-ink-faded"><MapPin className="h-3.5 w-3.5" />架构工作区</Link><a href={`/downloads/${item.slug}/terraform.zip`} download className="inline-flex items-center gap-1.5 rounded-lg border border-border px-3 py-2 text-xs text-ink-faded"><Download className="h-3.5 w-3.5" />Terraform 下载</a><a href={`/downloads/${item.slug}/docs.zip`} download className="inline-flex items-center gap-1.5 rounded-lg border border-border px-3 py-2 text-xs text-ink-faded"><Download className="h-3.5 w-3.5" />方案文档下载</a></div></article>)}</div></main>
}
